---
- name: update sudoers to allow /usr/local/bin
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - lineinfile: dest=/etc/sudoers regexp=^Default\s*'secure_path' line=Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin validate='visudo -cf %s'
