- name: Drop shell scritps for cluster_fix
  template:
    src: "{{ item }}"
    dest: /root/cluster_fix.sh
    owner: root
    group: root
    mode: 0755
  with_fileglob:
        - /etc/varsansible/templates/cluster_fix.j2