---
- name: Launch Testdb instance
  local_action:
    module: ec2
    region: us-east-1
    keypair: DevStack
    group: nightly-DB-test
    instance_type: m3.xlarge
    image: ami-ce4e24a6
    #vpc_subnet_id: subnet-e20152a4
    #assign_public_ip: yes
    count: 1
    wait: yes
  register: ec2
