---
- name: Drop requirements file
  template:
    src: "{{ item }}"
    dest: /home/ec2-user/requirements.txt
    owner: ec2-user
    group: ec2-user
    mode: 0644
  with_first_found:
    - files:
        - requirements.j2
      paths:
        - ../templates
