---
- name: Add test db instance to test db security group
  local_action: add_host hostname={{ item.public_ip }} groupname=nightly-DB-test
  with_items: ec2.instances
- name: tag as special
  local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
  with_items: ec2.instances
  args:
    tags:
      #Name: "{{ tagname }}"
      #Build: "{{ buildname }}"
      Name: TestName
      Build: 0012test
