---
- name: Add new Prod instances to migueltest-prod
  local_action: add_host hostname={{ item.public_ip }} groupname=migueltestgroup-prod
  with_items: ec2.instances
- name: tag as prod-
  local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
  with_items: ec2.instances
  args:
    tags:
      Name: "prod-"
