---
- name: Create elkstack security group
  local_action: 
    module: ec2_group
    name: migueltestgroup-elkstack
    description: Open access to ec2 test dev instances
    region: us-east-1
    vpc_id: vpc-d57664b7 
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 9300
        to_port: 9300
        cidr_ip: 0.0.0.0/0
