---
- name: Add new Stage instances to migueltest-stage
  local_action: add_host hostname={{ item.public_ip }} groupname=migueltestgroup-stage
  with_items: ec2.instances
- name: tag as stage-
  local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
  with_items: ec2.instances
  args:
    tags:
      Name: "stage-"
