---
- name: Add new Dev instances to migueltest-dev
  local_action: add_host hostname={{ item.public_ip }} groupname=migueltestgroup-elkstack
  with_items: ec2.instances
- name: tag as dev-
  local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
  with_items: ec2.instances
  args:
    tags:
      Name: "elkstack-kibana"
