---
- name: Drop shell scritps for pyntsall file
  template:
    src: "{{ item }}"
    dest: /var/tmp/setuptools_install.sh
    owner: miguel
    group: root
    mode: 0755
  with_fileglob:
        - ../templates/setuptools_install.j2
