---
- name: Configure Flaskapp node yum prereqs
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - include: tasks/yumprereqs.yml

- name: disable selinux
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - selinux: state=disabled

- name: update sudoers to allow /usr/local/bin
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - lineinfile: dest=/etc/sudoers regexp="^Defaults\s*secure_path" line="Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin" validate='visudo -cf %s'

- name: re enable selinux
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - selinux: policy=targeted state=enforcing
