---
- name: drop shell s3cmd scripts
  hosts: ["security_group__sc-{{ clustername }}"]
  remote_user: root
  vars_files: 
  - "/etc/varsansible/secretvars/starcluster_secret.yml"
  tasks:
    - include: tasks/s3config.yml

- name: fqvalidator install
  hosts: ["security_group__sc-{{ clustername }}"]
  gather_facts: False
  remote_user: root
  #sudo: True
  tasks:
  - shell: "cd /usr/bin && git clone https://github.com/statgen/fastQValidator.git"