---
- name: Configure Flaskapp node yum prereqs
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - include: tasks/yumprereqs.yml

- name: download Python-2.7.9
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - get_url: url=https://www.python.org/ftp/python/2.7.9/Python-2.7.9.tgz dest=/opt/Python-2.7.9.tgz mode=755

- name: disable selinux
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - selinux: state=disabled

- name: drop shell altpynstall scripts
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - include: tasks/shelldrop.yml
    - include: tasks/shelldrop2.yml

- name: shell work for altpyinstall
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - shell: ./altpynstall.sh >> altpylog.txt chdir=/opt

- name: download setuptools
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - get_url: url=https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py dest=/var/tmp

- name: install setuptools
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - shell: ./setuptools_install.sh >> setuptools_install_log.txt chdir=/var/tmp

- name: install virtualenv
  hosts: nodes
  user: miguel
  sudo: True
  tasks:
    - include: tasks/pipdrop.yml

- name: drop requirements in HOME
  hosts: nodes
  user: miguel
  tasks:
    - include: tasks/vboxrequirements_config.yml

- name: Create virtual env in HOME/virtualenvs
  hosts: nodes
  user: miguel
  #sudo: True
  tasks:
    - include: tasks/vboxflaskdrop.yml

- name: re enable selinux
  hosts: nodes
  remote_user: miguel
  sudo: True
  tasks:
    - selinux: policy=targeted state=enforcing
