---
- name: Provision dev nodes
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  #- include: tasks/security_group_create_dev.yml
  - include: tasks/launch_dev.yml
  - include: tasks/security_group_assign_dev.yml
  - name: pausing for spinup
    pause: seconds=90

#!#configure
- name: ensure jenkins present
  gather_facts: False
  hosts: ["Devstack"]
  remote_user: ec2-user
  sudo: True
  vars_files:
  - "/etc/varsansible/uservars/user_jenkins"
  roles:
  - mivok0.users

- name: ensure tomcat present
  gather_facts: False
  hosts: ["Devstack"]
  remote_user: ec2-user
  sudo: True
  vars_files:
  - "/etc/varsansible/uservars/user_tomcat"
  roles:
  - mivok0.users

- name: shell work tomcat folder creation
  gather_facts: False
  hosts: ["Devstack"]
  remote_user: tomcat
  sudo: False
  tasks:
  - file: path=/home/tomcat/ndar state=directory owner=tomcat group=tomcat

- name: Configure ndarweb dev
  gather_facts: False
  hosts: ["Devstack"]
  remote_user: ec2-user
  sudo: True
  vars_files:
  - "/etc/varsansible/appvars/dev_vars_tomcat.yml"
  - "/etc/varsansible/secretvars/dev_secrets_tomcat.yml"
  roles:
  - miguel.ndarweb

- name: update tomcat known_hosts
  hosts: ["Devstack"]
  remote_user: ec2-user
  sudo: True
  tasks:
    - lineinfile: dest=/home/tomcat/.ssh/known_hosts regexp="^54." line="54.165.18.92 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDk8P/Nh0dxyHcufi9YNWRzh24CuRZGOe4xkVSfjkA1owI+9oIz9VG0YEDnBL0zmzwREKUeU/nrraT5HBa4qFrG+7lmgzweB0NEGg24q6p50ufeVL8Q1X28i9hXw7v8dJ0kh8pvy66B3Z0vY5DoYl/ubziyxZQ1RO2IQWm6hdCgxBOD9TGb5r0iuVygxkMpA+GBLTKIe+UVfj6ndkoIt5Rw9jqt7fB5c2RV7QSjC6jGpdX59PQwtOI9GCcPUcFh8U3m34Lx1lOqa/0BBfT0IGK7fRqvd7LmvwW+laZVCeKyeyzUA6qDxhBdMYJ6Yd1y9v/yzBBXMLaMQZ1G+c8h1zm9"

- name: shell work for war movement
  gather_facts: False
  hosts: ["Devstack"]
  remote_user: tomcat
  sudo: False
  tasks:
  - shell: scp jenkins@jumphost:/home/jenkins/wars/ndarweb.war /home/tomcat/ndar/ndarweb.war chdir=/home/tomcat/ndar

- name: drop shell scripts
  gather_facts: False
  hosts: ["Devstack"]
  remote_user: tomcat
  sudo: False
  tasks:
    - include: tasks/curldeploy.yml

- name: deploy war
  gather_facts: False
  hosts: ["Devstack"]
  remote_user: tomcat
  sudo: False
  tasks:
  #- shell: curl –T /home/tomcat/ndar/ndarweb.war http://jenkins:zUKnJcuWAoTXtdzupStO@localhost:8080/manager/text/deploy?path=/&update=true >> curl.log chdir=/home/tomcat/ndar
  - shell: ./curldeploy.sh >> curl.log chdir=/home/tomcat/ndar