---
- name: Provision Jason Flask machine
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create security group
      local_action: 
        module: ec2_group
        name: Jason-Flask
        vpc_id: vpc-d57664b7
        description: Open access to ec2 test dev instances
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Rocket Launch Flask Dev
      local_action:
        module: ec2
        region: us-east-1
        keypair: DevStack
        group: Jason-Flask
        instance_type: t2.small
        image: ami-ea8fcc82
        vpc_subnet_id: subnet-e20152a4
        assign_public_ip: yes
        count: 1
        wait: yes
      register: ec2

    - name: Add instances to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=Jason-Flask
      with_items: ec2.instances

    - name: tag as flaskdev-
      local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
      with_items: ec2.instances
      args:
        tags:
          Name: "flaskdev-"

    - name: Wait for ssh you derp
      pause: minutes=1

- name: libffi requirement
  hosts: Jason-Flask
  user: ec2-user
  sudo: True
  tasks:
    - include: tasks/drop_libffi-devel.yml

- name: drop requirements in HOME
  hosts: Jason-Flask
  user: ec2-user
  tasks:
    - include: tasks/requirements_config.yml

- name: Create virtual env in HOME/virtualenvs
  hosts: Jason-Flask
  user: ec2-user
  #sudo: True
  tasks:
    - include: tasks/flaskdrop.yml

#- name: Clone flask code repo
#  hosts: Jason-Flask
#  user: ec2-user
#  tasks:
#    - include: tasks/gitflask.yml
