---
- name: Test provision server
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Create security group
      local_action: 
        module: ec2_group
        name: migueltestgroup
        description: Open access to ec2 test dev instances
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: Rocket Launch Dev
      local_action:
        module: ec2
        region: us-east-1
        keypair: DevStack
        group: migueltestgroup
        instance_type: m1.small
        image: ami-9ab6f0f2
        count: 2
        wait: yes
      register: ec2

    - name: Add migueltestgroup instances to host group
      local_action: add_host hostname={{ item.public_ip }} groupname=migueltestgroup
      with_items: ec2.instances

    - name: tag as dev-
      local_action: ec2_tag resource={{ item.id }} region=us-east-1 state=present
      with_items: ec2.instances
      args:
        tags:
          Name: "dev-"

    - name: Wait for ssh you derp
      pause: minutes=1

- name: Configure new dev nodes
  hosts: migueltestgroup
  user: martinezme2
  sudo: True
  tasks:
    - include: tasks/dropsomepkgs.yml
