---
- name: Provision 3 hosts 1 each dev stage prod
  hosts: 127.0.0.1
  connection: local
  tasks:
#  - include: tasks/security_group_create_dev.yml
#  - include: tasks/security_group_create_stage.yml
  - include: tasks/security_group_create_prod.yml
#  - include: tasks/launch_dev.yml
#  - include: tasks/security_group_assign_dev.yml
#  - include: tasks/launch_stage.yml
#  - include: tasks/security_group_assign_stage.yml
  - include: tasks/launch_prod.yml
  - include: tasks/security_group_assign_prod.yml
  - name: 1 min pause
    pause: minutes=1

#!#configure
- name: ensure jenkins and tomcat users present-dev
  hosts: ["migueltestgroup-prod"]
  remote_user: ec2-user
  sudo: True
  vars:
  - users:
     - username: jenkins
       name: jenkins
       groups: []
       uid: 9901
       ssh_key:
           - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDvrr170SCTpihdQ91U9vg2cXh7+5T04AXbQrLPHYZcvN5Ay7zbko1O37glXwThN0Q++tGGnNyyodpbriHh722H6QwYCy+YY8WjwZKABH3b64MemEbB1bRWjc6ViJxc3a7eTdGylufHyWvknVb+wD11y4hOYTOj0AHGlqY0vLmcWRSoyBbPzcA0Q8chT26ILzCTzx1enE/f1uXhgz6naVRStfkDgaVXFhPEZlbsbpx3Q+Rz6+ccPQSbz2kVO87na7kfbM/MmrMmmCybZmLWSx05oYjIA/CZ1+KLLYv1QLjdjBvEfdzendc+Cg6MUa5f4WtSpWDyyPIyU9Os2J0hl+MB"
     - username: tomcat
       name: tomcat
       groups: []
       uid: 9909
       ssh_key:
           - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDvrr170SCTpihdQ91U9vg2cXh7+5T04AXbQrLPHYZcvN5Ay7zbko1O37glXwThN0Q++tGGnNyyodpbriHh722H6QwYCy+YY8WjwZKABH3b64MemEbB1bRWjc6ViJxc3a7eTdGylufHyWvknVb+wD11y4hOYTOj0AHGlqY0vLmcWRSoyBbPzcA0Q8chT26ILzCTzx1enE/f1uXhgz6naVRStfkDgaVXFhPEZlbsbpx3Q+Rz6+ccPQSbz2kVO87na7kfbM/MmrMmmCybZmLWSx05oYjIA/CZ1+KLLYv1QLjdjBvEfdzendc+Cg6MUa5f4WtSpWDyyPIyU9Os2J0hl+MB"
  roles:
  - mivok0.users

#- name: Configure webapp dev
  #hosts: migueltestgroup-dev
  #remote_user: ec2-user
  #sudo: True
  #vars_files:
  #- "vars/dev_vars_tomcat.yml"
  #- "vars/dev_secrets_tomcat.yml"
  #roles:
  #- miguel.webapp

#- name: Configure webapp stage
  #hosts: migueltestgroup-stage
  #remote_user: ec2-user
  #sudo: True
  #vars_files:
  #- "vars/stage_vars_tomcat.yml"
  #- "vars/stage_secrets_tomcat.yml"
  #roles:
  #- miguel.webapp

- name: Configure webapp prod
  hosts: migueltestgroup-prod
  remote_user: ec2-user
  sudo: True
  vars_files:
  - "vars/prod_vars_tomcat.yml"
  - "vars/prod_secrets_tomcat.yml"
  roles:
  - miguel.webapp
