---
- name: Provision dev nodes
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  #- include: tasks/security_group_create_dev.yml
  - include: tasks/launch_dev.yml
  - include: tasks/security_group_assign_dev.yml
  - name: pausing for spinup
    pause: seconds=90

#!#configure
- name: ensure jenkins present
  gather_facts: False
  hosts: ["{{ aws key var }}"]
  remote_user: ec2-user
  sudo: True
  vars_files:
  - "/etc/varsansible/uservars/user_jenkins"
  roles:
  - mivok0.users

- name: ensure tomcat present
  gather_facts: False
  hosts: ["{{ aws key var }}"]
  remote_user: ec2-user
  sudo: True
  vars_files:
  - "/etc/varsansible/uservars/user_tomcat"
  roles:
  - mivok0.users

- name: shell work tomcat folder creation
  gather_facts: False
  hosts: ["{{ aws key var }}"]
  remote_user: tomcat
  sudo: False
  tasks:
  - file: path=/home/tomcat/webapp state=directory owner=tomcat group=tomcat

- name: Configure webappweb dev
  gather_facts: False
  hosts: ["{{ aws key var }}"]
  remote_user: ec2-user
  sudo: True
  vars_files:
  - "/etc/varsansible/appvars/dev_vars_tomcat.yml"
  - "/etc/varsansible/secretvars/dev_secrets_tomcat.yml"
  roles:
  - miguel.webappweb

- name: update tomcat known_hosts
  hosts: ["{{ aws key var }}"]
  remote_user: ec2-user
  sudo: True
  tasks:
  - lineinfile: dest=/home/tomcat/.ssh/known_hosts regexp="^ {{ hostname }}" line="{{ hostname }} {{ key variable }}"

- name: shell work for war movement
  gather_facts: False
  hosts: ["{{ aws key var }}"]
  remote_user: tomcat
  sudo: False
  tasks:
  - shell: scp jenkins@jumphost:/home/jenkins/wars/webappweb.war /home/tomcat/webapp/webappweb.war chdir=/home/tomcat/webapp

- name: drop shell scripts
  gather_facts: False
  hosts: ["{{ aws key var }}"]
  remote_user: tomcat
  sudo: False
  tasks:
    - include: tasks/curldeploy.yml

- name: deploy war
  gather_facts: False
  hosts: ["{{ aws key var }}"]
  remote_user: tomcat
  sudo: False
  tasks:
  #- shell: curl –T /home/tomcat/webapp/webappweb.war http://jenkins:zUKnJcuWAoTXtdzupStO@localhost:8080/manager/text/deploy?path=/&update=true >> curl.log chdir=/home/tomcat/webapp
  - shell: ./curldeploy.sh >> curl.log chdir=/home/tomcat/webapp
